Ensuring dependencies in build scripts

diff --git a/Scripts/docs b/Scripts/docs
--- a/Scripts/docs
+++ b/Scripts/docs
@@ -1,5 +1,12 @@
 #!/bin/bash -e
 echo $0
+
+# ensure doxygen is installed
+command -v doxygenXXX >/dev/null 2>&1 || {
+    echo >&2 "Error: doxygen not found! doxygen is required to generate docsets. Try \"brew install doxygen\".";
+    exit 1;
+}
+
 source "$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)/consts"
 
 DOXYFILE_HTML="${DOCS_RES}/html.doxyfile"
